### ISSUE TITLE
Positional Information

### ISSUE THREAD

**Issue by indietyp** [01mf02/hifijson#2]
Hi 👋 I am currently looking for a JSON parser, that is correct, while still being flexible and hifijson seems to tick all the boxes, although I have some questions about it's capabilities.

For the current use-case I am considering, I am in need of positional information, is it possible to provide this with the existing lexers? I thought about implementing a lexer myself, but `Read` seems to be unimplementable by external crates, which prevented me from doing so.

Thanks!

**Comment by indietyp** [comment]
Another possibility would be to have something like `into_inner(self) -> &'a [u8]` or `as_inner(&self) -> &'a [u8]` on the `SliceIterator`, using that one would be able to get the amount of bytes read through:

```
let source: &[u8] = ...;
let lexer = SliceLexer::new(source);
// ... do some operations
let bytes_read = (lexer.as_ptr() as usize) - (source.as_ptr() as usize)
```

That would rely on the guarantee that the inner slice is never replaced, only advanced, but would mean that virtually no code would need to be changed.

**Comment by 01mf02** [comment]
Thanks for this excellent suggestion.
I followed the convention used also in [`slice::Iter`](https://doc.rust-lang.org/std/slice/struct.Iter.html) and called the method `SliceLexer::as_slice()`.
